--T1.4.1.Creacion_Documentos.sql

--4.1 Sentencia o consulta de creación del documento
--Observación: Escriba el código en MongoDB para crear al menos 20 documentos que correspondan a su conjunto de
--datos específico. Almacene en el repositorio el script con el nombre de T1.4.1.Creacion_Documentos.sql

db.Medicion.insertMany([
{
	"Measurment_Date" : ISODate("2017-01-01T05:00:00Z"),
	"Station_Code" : "101",
	"Item_Code" : "1",
	"Average_Value" : 0.004,
	"Instrument_Status" : "2",
	"Item_Name" : "SO2",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Jongno-gu",
	"Address_Station" : "19; Jong-ro 35ga-gil; Jongno-gu; Seoul; Republic of Korea",
	"Latitude" : 37.572016,
	"Longitude" : 127.50075
},
{
	"Measurment_Date" : ISODate("2017-01-01T06:00:00Z"),
	"Station_Code" : "101",
	"Item_Code" : "1",
	"Average_Value" : 0.004,
	"Instrument_Status" : "2",
	"Item_Name" : "SO2",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Jongno-gu",
	"Address_Station" : "19; Jong-ro 35ga-gil; Jongno-gu; Seoul; Republic of Korea",
	"Latitude" : 37.572016,
	"Longitude" : 127.50075
},
{
	"Measurment_Date" : ISODate("2017-01-01T07:00:00Z"),
	"Station_Code" : "101",
	"Item_Code" : "1",
	"Average_Value" : 0.004,
	"Instrument_Status" : "2",
	"Item_Name" : "SO2",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Jongno-gu",
	"Address_Station" : "19; Jong-ro 35ga-gil; Jongno-gu; Seoul; Republic of Korea",
	"Latitude" : 37.572016,
	"Longitude" : 127.50075
},
{
	"Measurment_Date" : ISODate("2017-01-01T08:00:00Z"),
	"Station_Code" : "101",
	"Item_Code" : "1",
	"Average_Value" : 0.004,
	"Instrument_Status" : "2",
	"Item_Name" : "SO2",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Jongno-gu",
	"Address_Station" : "19; Jong-ro 35ga-gil; Jongno-gu; Seoul; Republic of Korea",
	"Latitude" : 37.572016,
	"Longitude" : 127.50075
},
{
	"Measurment_Date" : ISODate("2017-01-01T09:00:00Z"),
	"Station_Code" : "101",
	"Item_Code" : "1",
	"Average_Value" : 0.003,
	"Instrument_Status" : "2",
	"Item_Name" : "SO2",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Jongno-gu",
	"Address_Station" : "19; Jong-ro 35ga-gil; Jongno-gu; Seoul; Republic of Korea",
	"Latitude" : 37.572016,
	"Longitude" : 127.50075
},
{
	"Measurment_Date" : ISODate("2017-01-01T10:00:00Z"),
	"Station_Code" : "101",
	"Item_Code" : "1",
	"Average_Value" : 0.003,
	"Instrument_Status" : "2",
	"Item_Name" : "SO2",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Jongno-gu",
	"Address_Station" : "19; Jong-ro 35ga-gil; Jongno-gu; Seoul; Republic of Korea",
	"Latitude" : 37.572016,
	"Longitude" : 127.50075
},
{
	"Measurment_Date" : ISODate("2017-01-01T11:00:00Z"),
	"Station_Code" : "101",
	"Item_Code" : "1",
	"Average_Value" : 0.003,
	"Instrument_Status" : "2",
	"Item_Name" : "SO2",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Jongno-gu",
	"Address_Station" : "19; Jong-ro 35ga-gil; Jongno-gu; Seoul; Republic of Korea",
	"Latitude" : 37.572016,
	"Longitude" : 127.50075
},
{
	"Measurment_Date" : ISODate("2017-01-01T05:00:00Z"),
	"Station_Code" : "104",
	"Item_Code" : "1",
	"Average_Value" : 0.005,
	"Instrument_Status" : "2",
	"Item_Name" : "SO2",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Eunpyeong-gu",
	"Address_Station" : "215; Jinheung-ro; Eunpyeong-gu; Seoul; Republic of Korea",
	"Latitude" : 37.6098232,
	"Longitude" : 126.9348476
},
{
	"Measurment_Date" : ISODate("2017-01-01T06:00:00Z"),
	"Station_Code" : "104",
	"Item_Code" : "1",
	"Average_Value" : 0.005,
	"Instrument_Status" : "2",
	"Item_Name" : "SO2",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Eunpyeong-gu",
	"Address_Station" : "215; Jinheung-ro; Eunpyeong-gu; Seoul; Republic of Korea",
	"Latitude" : 37.6098232,
	"Longitude" : 126.9348476
},
{
	"Measurment_Date" : ISODate("2017-01-01T07:00:00Z"),
	"Station_Code" : "104",
	"Item_Code" : "1",
	"Average_Value" : 0.005,
	"Instrument_Status" : "2",
	"Item_Name" : "SO2",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Eunpyeong-gu",
	"Address_Station" : "215; Jinheung-ro; Eunpyeong-gu; Seoul; Republic of Korea",
	"Latitude" : 37.6098232,
	"Longitude" : 126.9348476
},
{
	"Measurment_Date" : ISODate("2017-01-01T08:00:00Z"),
	"Station_Code" : "104",
	"Item_Code" : "1",
	"Average_Value" : 0.005,
	"Instrument_Status" : "2",
	"Item_Name" : "SO2",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Eunpyeong-gu",
	"Address_Station" : "215; Jinheung-ro; Eunpyeong-gu; Seoul; Republic of Korea",
	"Latitude" : 37.6098232,
	"Longitude" : 126.9348476
},
{
	"Measurment_Date" : ISODate("2017-01-01T09:00:00Z"),
	"Station_Code" : "104",
	"Item_Code" : "1",
	"Average_Value" : 0.004,
	"Instrument_Status" : "2",
	"Item_Name" : "SO2",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Eunpyeong-gu",
	"Address_Station" : "215; Jinheung-ro; Eunpyeong-gu; Seoul; Republic of Korea",
	"Latitude" : 37.6098232,
	"Longitude" : 126.9348476
},
{
	"Measurment_Date" : ISODate("2017-01-01T10:00:00Z"),
	"Station_Code" : "104",
	"Item_Code" : "1",
	"Average_Value" : 0.004,
	"Instrument_Status" : "2",
	"Item_Name" : "SO2",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Eunpyeong-gu",
	"Address_Station" : "215; Jinheung-ro; Eunpyeong-gu; Seoul; Republic of Korea",
	"Latitude" : 37.6098232,
	"Longitude" : 126.9348476
},
{
	"Measurment_Date" : ISODate("2017-01-01T11:00:00Z"),
	"Station_Code" : "104",
	"Item_Code" : "1",
	"Average_Value" : 0.005,
	"Instrument_Status" : "2",
	"Item_Name" : "SO2",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Eunpyeong-gu",
	"Address_Station" : "215; Jinheung-ro; Eunpyeong-gu; Seoul; Republic of Korea",
	"Latitude" : 37.6098232,
	"Longitude" : 126.9348476
},
{
	"Measurment_Date" : ISODate("2017-01-01T05:00:00Z"),
	"Station_Code" : "115",
	"Item_Code" : "5",
	"Average_Value" : 1.3,
	"Instrument_Status" : "2",
	"Item_Name" : "CO",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Yangcheon-gu",
	"Address_Station" : "56; Jungang-ro 52-gil; Yangcheon-gu; Seoul; Republic of Korea",
	"Latitude" : 37.5259388,
	"Longitude" : 126.856603
},
{
	"Measurment_Date" : ISODate("2017-01-01T06:00:00Z"),
	"Station_Code" : "115",
	"Item_Code" : "5",
	"Average_Value" : 1.3,
	"Instrument_Status" : "2",
	"Item_Name" : "CO",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Yangcheon-gu",
	"Address_Station" : "56; Jungang-ro 52-gil; Yangcheon-gu; Seoul; Republic of Korea",
	"Latitude" : 37.5259388,
	"Longitude" : 126.856603
},
{
	"Measurment_Date" : ISODate("2017-01-01T07:00:00Z"),
	"Station_Code" : "115",
	"Item_Code" : "5",
	"Average_Value" : 1.2,
	"Instrument_Status" : "2",
	"Item_Name" : "CO",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Yangcheon-gu",
	"Address_Station" : "56; Jungang-ro 52-gil; Yangcheon-gu; Seoul; Republic of Korea",
	"Latitude" : 37.5259388,
	"Longitude" : 126.856603
},
{
	"Measurment_Date" : ISODate("2017-01-01T08:00:00Z"),
	"Station_Code" : "115",
	"Item_Code" : "5",
	"Average_Value" : 1.3,
	"Instrument_Status" : "2",
	"Item_Name" : "CO",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Yangcheon-gu",
	"Address_Station" : "56; Jungang-ro 52-gil; Yangcheon-gu; Seoul; Republic of Korea",
	"Latitude" : 37.5259388,
	"Longitude" : 126.856603
},
{
	"Measurment_Date" : ISODate("2017-01-01T09:00:00Z"),
	"Station_Code" : "115",
	"Item_Code" : "5",
	"Average_Value" : 1.1,
	"Instrument_Status" : "2",
	"Item_Name" : "CO",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Yangcheon-gu",
	"Address_Station" : "56; Jungang-ro 52-gil; Yangcheon-gu; Seoul; Republic of Korea",
	"Latitude" : 37.5259388,
	"Longitude" : 126.856603
},
{
	"Measurment_Date" : ISODate("2017-01-01T10:00:00Z"),
	"Station_Code" : "115",
	"Item_Code" : "5",
	"Average_Value" : 1.1,
	"Instrument_Status" : "2",
	"Item_Name" : "CO",
	"Unit_of_Measurement" : "ppm",
	"Pollutant_Status" : "Good",
	"Description" : "Normal functioning",
	"Station_Name" : "Yangcheon-gu",
	"Address_Station" : "56; Jungang-ro 52-gil; Yangcheon-gu; Seoul; Republic of Korea",
	"Latitude" : 37.5259388,
	"Longitude" : 126.856603
}
])